name: example
description: A sample for to_string usage.
homepage: https://github.com/lvsecoto/to_string
version: 1.0.0
author: lvsecoto <lvsecoto@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  to_string: ^1.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.7.1
  to_string_generator: ^1.0.0
