name: to_string_generator
description: Builder and Generator for package to_string
version: 0.0.1
author: lvsecoto <lvsecoto@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  build: ^1.2.0
  source_gen: ^0.9.4+5
  analyzer: ^0.38.5

  to_string:
    path: '../to_string'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.7.1
  source_gen_test: ^0.1.0+5
